# 查看所有配置:https://gohugobrasil.netlify.app/getting-started/configuration/#toml-configuration
baseURL = "https://it-boyer.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "七习--高效能人士"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-icarus"
enableGitInfo = true # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
contentDir = "content"
publishdir = "public"

# Comment the themesDir option if you use this theme in production
#themesDir = "../.."


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "John Doe"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](https://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "you@example.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "主页"
    link   = "/"

[[params.menu]]
    before = false
    label  = "标签"
    link   = "tags/"
    
[[params.menu]]
    before = false
    label  = "分类"
    link   = "categories/"
    
[[params.menu]]
    before = false
    label  = "归档"
    link   = "/post/"
    
[[params.menu]]
    before = false
    label  = "文档"
    link   = "/idocs/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/gohugoio"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "gohugoio"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "gohugoio"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
