name: Build README

on:
  push:
    branches:
      - main # Set a branch to deploy
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # 生成wakatime
      - name: wakatime-charts
        uses: athul/waka-readme@master
        with:
          BRANCH_NAME: main # 当前库的分支
          COMMIT_MESSAGE: "生成wakatime统计"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.IT_BOT_KEY }} # only required if using the action in repository other than profile
          REPOSITORY: it-boyer/it-boyer
          TIME_RANGE: "last_7_days"

      # 生成README
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        env:
          BOT_TOKEN: ${{ secrets.IT_BOT_KEY }}
        run: |-
          python build_readme.py
          # cat README.md
          cp README.* resume/static

      # 使用 hugo 发布
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --config config_resume.toml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          # 再gh-page发布库设置－deploy中
          # 添加ssh公钥
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # 博客源码库中secret－action中
          # 添加ssh私钥，名称ACTIONS_DEPLOY_KEY
          deploy_key: ${{ secrets.DEPLOY_TO_IT_BOYER_PAGES }}
          publish_dir: ./docs # 对应config.toml配置publish_dir
          external_repository: it-boyer/it-boyer
          publish_branch: gh-pages # default: gh-pages
          force_orphan: true
