name: Create Issue

on:
  workflow_dispatch: # 手动触发action
    inputs:
      issue_title:
        description: "任务标题"
        required: true
        default: "todo.."
        type: string #支持的类型： string number boolean choice environment
      issue_body:
        description: "任务内容描述"
        required: true
        default: "todo..."
        type: string
      issue_label:
        description: "tags"
        required: true
        default: "todo"
        type: string
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.issue_title }}
          body: ${{ inputs.issue_body }}
          labels: ${{ inputs.issue_label }}
          assignees: "it-boyer"
          emoji: "+1"
